client.go
When running from a service, each `client.New` call will [append one more entry](https://github.com/containerd/nri/blob/5e52908d1c3c2b4c67e92a8781010257695c065e/client.go#L32) to PATH.
Indirectly this affects fork/exec calls (the error message is a bit misleading, ideally
it should be something like "argument list and environment are too long").
The problem can be reproduced with the following test:
```
func TestNewClient(t *testing.T) {
for i := 0; i < 11000; i++ {
_, err := New();
if err != nil {
t.Fatal(err)
}
_, err = exec.Command("true").CombinedOutput()
if err != nil {
t.Fatal(err)
}
}
}
--- FAIL: TestNewClient (7.84s)
client_test.go:17: fork/exec /usr/bin/true: argument list too long
FAIL
exit status 1
```
In cri-containerd I observed this error after launching ~50 pods …
=> Fix "argument list too long" error.

client.go, skel/skel.go, types/v1/types.go
Merge the PluginError struct into Result. This allows the NRI skeleton and invocation to encode and un-marshal to a single type and cleans up the code a bit.
Error messages from injected errors:
```
nri invoke: plugin: testplugin: injected structured error
```
```
nri invoke: plugin: testplugin: failed to unmarshal plugin output: unexpected end of JSON input: output: <empty> exit code: 1
```
```
nri invoke: plugin: testplugin: failed to unmarshal plugin output: invalid character 'i' looking for beginning of value: output: "injected invalid output"
```
```
nri invoke: plugin: testplugin: exec: "missing": executable file not found in $PATH
```
Signed-off-by: Deep Debroy <ddebroy@apple.com>
=> Merge PluginError into Result

Makefile, client.go, skel/skel.go, types/v1/types.go
To apply the Apache 2.0 license, either a NOTICE and/or license
headers must be added to the source code;
To apply the Apache License to your work, attach the following
boilerplate notice, with the fields enclosed by brackets "[]"
replaced with your own identifying information. (Don't include
the brackets!)  The text should be enclosed in the appropriate
comment syntax for the file format. We also recommend that a
file or class name and description of purpose be included on the
same "printed page" as the copyright notice for easier
identification within third-party archives.
=> Fix licensing (add license headers)

README.md
Use 2 spaces for indentation instead of mixed tabs/spaces, which didn't render nicely on GitHub
=> README: fix JSON syntax-error, and reformat JSON examples

go.mod, go.sum
Upgrade containerd to 1.5.2
Signed-off-by: Manuel Alejandro de Brito Fontes aledbf@gmail.com
=> Bump containerd to 1.5.2

.github/workflows/ci.yml, .golangci.yml
Update actions runner OS from Ubuntu 18.04 to Ubuntu 22.04. Update actions/checkout, actions/setup-go, and golangci/golangci-lint-action packages from v2 to v3. Update golangci/golangci-lint from v1.29 to v1.50.1. Remove deprecated linters.
Related issue: https://github.com/containerd/project/issues/95
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
=> Update GitHub actions CI workflow

README.md
Signed-off-by: Mike Brown <brownwm@us.ibm.com>
=> add back project info

pkg/adaptation/plugin_linux.go, pkg/adaptation/plugin_other.go, pkg/net/socketpair_unix.go, pkg/net/socketpair_windows.go, pkg/runtime-tools/generate/helpers_linux.go, pkg/runtime-tools/generate/helpers_other.go
Signed-off-by: Wei Fu <fuweid89@gmail.com>
=> chore: cleanup old buildtags by `go fix`

pkg/adaptation/plugin.go
Fix incorrect formatting verbs for error logging.
=> pkg/adaptaton: log errors with %v not %w.

pkg/adaptation/adaptation.go, pkg/adaptation/adaptation_suite_test.go, pkg/adaptation/plugin.go
Set up adaptation pointer properly during plugin creation/connection acceptance to fix a panic when a plugin sends an unsolicited container update. Also make sure that we get initialized with valid, non-nil function pointers.
=> adaptation: fix a panic for unsolicited updates.

pkg/adaptation/adaptation_suite_test.go, pkg/adaptation/suite_test.go, pkg/stub/stub.go
Don't crash a plugin if it tries to use `stub.UpdateContainers()` without `Start()`ing the stub first. It has no/a nil runtime service at that point.
=> stub: fix a potential plugin crash.

pkg/adaptation/adaptation.go, pkg/adaptation/plugin.go, pkg/api/plugin.go
Update defaults for plugin registration and request processing timeouts and make them configurable. This should help testing plugins with a complex startup/registration sequence in very slow CI environments where registration otherwise sometimes triggers a timeout.
Also adjust the default socket path to `/var/run/nri/nri.sock` and create the parent directory for the socket with `0700` access rights instead of `0755`. Having an intermediate directory makes it easier for plugins that run as a K8s daemonset to survive a runtime restart an reconnect to the NRI socket.
=> Make plugin timeouts configurable, adjust default socket path.

pkg/adaptation/result.go
Fix mount and device adjustment for container create request processing. Mounts in the NRI create request got incorrectly reset if a plugin ever modifed mounts. All subsequent plugins received incorrect mount data in their creation request. The same bug was present for device adjustment.
Note that this had a direct effect on the NRI creation request but not the actual container itself.
=> adaptation: fix mount and device adjustment.

pkg/runtime-tools/generate/generate.go, pkg/runtime-tools/generate/generate_suite_test.go
When adjusting CPU or memory resources, check for each field whether it is set (IOW adjusted by a plugin) before updating. The field getters return the corresponding golang zero value for unset fields. Therefore unconditionally adjusting unset Spec fields resets the fields instead. This manifests itself by all container CPU resources getting cleared when NRI is enabled but no plugins are running or none of the running plugins are adjust resources.
=> fixes: fix resource adjustment to properly ignore unset/unadjusted fields.

pkg/api/mount.go, pkg/runtime-tools/generate/generate.go, pkg/runtime-tools/generate/generate_suite_test.go
If mounts get adjusted, sort the final mount slice to make sure that any potential subdirectories are mounted only after their parents. Otherwise a parent mount could shadow/mask the content of a previously mounted subdirectory.
=> fixes: sort final adjusted mount slice.

.github/workflows/ci.yml, go.mod
Update minimum Go version to Go 1.19 in go.mod. Update golangci-lint to
v1.51.x for Go 1.20 support.
Signed-off-by: Austin Vazquez <macedonv@amazon.com>
=> Add Go 1.20 support to CI

pkg/api/resources.go
When converting to OCI LinuxResources, always use an empty `&LinuxMemory{}` instead of a `nil` one. Some runtimes try to dereference it unconditionally. Leaving it unset panics on these.
=> api: initialize OCI LinuxMemory resources to empty.

README.md
Add a few paragraphs with security considerations about protecting access to the NRI socket and deploying NRI plugins as K8s DaemonSets.
=> docs: add a chapter about security considerations.

Makefile
Fix 'install-*' Makefile targets to properly install and compile the various protoc toolchain binaries and plugins.
=> Makefile: fix 'install-*' targets.

pkg/adaptation/plugin.go, pkg/stub/stub.go
The environment variable `NRI_PLUGIN_NAME` actually represents name in the plugin
https://github.com/containerd/nri/blob/83295992ed466e5589a1a83ba3ad2bd6b6feb199/pkg/stub/stub.go#L273-L280
https://github.com/containerd/nri/blob/83295992ed466e5589a1a83ba3ad2bd6b6feb199/pkg/stub/stub.go#L450-L452
so if we pass `plugin name`(`< idx >-< base name >`), the log will print out 'plugin name' with duplicate `idx`.
```
time="2023-05-18T13:39:43+08:00" level=info msg="Subscribing plugin 03-03-logger (03-logger) for events RunPodSandbox,StopPodSandbox,RemovePodSandbox,CreateContainer,PostCreateContainer,StartContainer,PostStartContainer,UpdateContainer,PostUpdateContainer,StopContainer,RemoveContainer"
time="2023-05-18T13:39:43+08:00" level=info msg="Started plugin 03-03-logger..."
```
Note that …
=> fix the `NRI_PLUGIN_NAME` env value when launching a pre-installed plugin

pkg/api/event.go
the keys in code's bits map is lowercase
```
bits := map[string]Event{
"runpodsandbox":       Event_RUN_POD_SANDBOX,
"stoppodsandbox":      Event_STOP_POD_SANDBOX,
"removepodsandbox":    Event_REMOVE_POD_SANDBOX,
"createcontainer":     Event_CREATE_CONTAINER,
"postcreatecontainer": Event_POST_CREATE_CONTAINER,
"startcontainer":      Event_START_CONTAINER,
"poststartcontainer":  Event_POST_START_CONTAINER,
"updatecontainer":     Event_UPDATE_CONTAINER,
"postupdatecontainer": Event_POST_UPDATE_CONTAINER,
"stopcontainer":       Event_STOP_CONTAINER,
"removecontainer":     Event_REMOVE_CONTAINER,
}
```
so should fix if strings.Contains(name, "Pod") => if strings.Contains(name, "pod")
=> Fix ParseEventMask to produce proper masks for 'pod' and 'container' shorthand event notations.

README.md, RELEASES.md, pkg/adaptation/adaptation_suite_test.go, pkg/adaptation/suite_test.go, pkg/stub/stub.go, plugins/device-injector/device-injector.go, plugins/differ/nri-differ.go, plugins/hook-injector/hook-injector.go, plugins/logger/nri-logger.go, plugins/template/plugin.go, plugins/v010-adapter/v010-adapter.go
Don't hide the ttRPC request context from plugins. Pass the context on to the plugin's request handler. Once we have opentelemetry ttRPC instrumentation support, this should allow us to properly propagate trace spans and have detailed instrumentation on the plugins side properly nested into the related original request on the runtime side.
While making API-breaking changes, also fix UpdateContainer adding an argument with the updated resources.
Update sample plugins and tests with the updated interfaces and add basic tests for UpdateContainer which we lacked so far.
=> stub: pass context to plugins, pass updated resources to UpdateContainers.

.github/workflows/ci.yml
Add a job to do a simple test build as part of the CI workflow. This should make sure that PRs don't break building any of the sample plugins.
=> .github: add test build to CI workflow.

pkg/net/socketpair_cloexec_linux.go, pkg/net/socketpair_cloexec_unix.go, pkg/net/socketpair_unix.go
We were calling the close() syscall multiple time
with the same fd number, leading to random issues like
closing containerd stream port.
In newLaunchedPlugin() we have:
```
sockets, _ := net.NewSocketPair()
defer sockets.Close()
conn, _ := sockets.LocalConn()
peerFile := sockets.PeerFile()
defer func() {
peerFile.Close()
if retErr != nil {
conn.Close()
}
}()
cmd.Start()
```
so we were doing:
```
close(local) (in LocalConn())
cmd.Start()
close(peer) (peerFile.Close())
close(local) (sockets.Close())
close(peer) (sockets.Close())
```
If the NRI plugin that we launch with cmd.Start() is not cached or
the system is a bit busy, cmd.Start() gives a large enough window
for another goroutine to open a file that will get the same fd number
as local was, thus being closed by accident.
Fix the …
=> socketpair_unix: avoid double close(), set FD_CLOEXEC

examples/go.mod, examples/go.sum, go.mod, go.sum, plugins/device-injector/go.mod, plugins/device-injector/go.sum, plugins/differ/go.mod, plugins/differ/go.sum, plugins/hook-injector/go.mod, plugins/hook-injector/go.sum, plugins/logger/go.mod, plugins/logger/go.sum, plugins/template/go.mod, plugins/template/go.sum, plugins/ulimit-adjuster/go.mod, plugins/ulimit-adjuster/go.sum, plugins/v010-adapter/go.mod, plugins/v010-adapter/go.sum
- relates to https://github.com/containerd/containerd/pull/9743#discussion_r1477058823
- replaces / closes https://github.com/containerd/nri/pull/70
full diff: https://github.com/containerd/ttrpc/compare/baadfd8e7956...v1.2.3
=> go.mod: github.com/containerd/ttrpc v1.2.3

pkg/adaptation/adaptation.go
During NRI external plugin registration:
* acceptPluginConnections() is called
* adaptation lock from `nri/pkg/adaptation` is acquired
* `syncFn` is invoked
* `syncFn` acquires NRI lock in `pkg/nri/nri.go`
During container lifecycle events such as `ContainerStart`
* NRI lock is acquired in pkg/nri.go
* adaptation lock is acquired in `StateChange()` in `nri/pkg/adaptation`
As a result, the locking order during NRI plugin registration is:
* adaptation lock -> NRI lock
While the locking order during container starts is:
* NRI lock -> adaptation lock
Due the fact that the locking order is inverted and not consistent, it it possible to encounter a deadlock.
To fix the issue, during NRI plugin registration, first acquire the NRI lock (done via `syncFn` call) and only after acquire the …
=> Fix deadlock during NRI plugin registration

plugins/hook-injector/hook-injector.go
As mentioned in hook-injector plugin README, this plugin achieves CRI-O compatible hooks injection. However, there is a difference between this implementation and CRI-O's implementation as CRI-O watches hook directories for any changes which allows for new hooks to be added to new containers. This is not the case here where this plugin only uses hooks created while the plugin is first running. So, they are not really compatible. [Reference CRI-O code](https://github.com/cri-o/cri-o/blob/5ab50a9b6c6152d8eae4850b2668ff82c0b2b67a/cmd/crio/main.go#L385-L396).
Also, there are some use-cases where services set up their hooks after the cluster and the plugin are up. CRI-O would register these new hooks but again the plugin currently won't. This PR aims to fix that.
We can also make this optional …
=> Modify hook-injector plugin to monitor directories to match cri-o

plugins/template/plugin.go
Fix a small typo in the comments for `CreateContainer` in the template plugin. Spotted while reviewing #94.
=> plugins/template: fix a typo in a comment.

pkg/adaptation/adaptation.go
Most of Adaptation's methods call removeClosedPlugins to remove closed plugins, which are moved out of the r.plugins list and never operated on again.
It may remain a zombie process on the system, and using some tools it will look like the plugin is running normally.
```console
...
├─containerd─┬─03-logger
│            └─15*[{containerd}]
```
This pr causes `removeClosedPlugins` to call `plugin.stop` when removing closed plugins, which avoids these zombie processes.
=> stop closed plugins that will be removed

pkg/stub/stub.go
In some scenarios such as runtime restart or the occurrence of nri request timeout, the ttrpc connections between the plugin and the runtime will be actively closed by the runtime, even the underlying network connection will be closed together. After this, the plugin must need to re-register to the adaptation side, but now the stub object cannot be reused for this; if the running plugin wants to reconnect to the runtime, the only way is to create a new stub for the plugin.
This commit introduce a new stub option `WithAutoRestartDelay`. The plugin developer can use this to build a reuseable stub, which will wait for a confiurable time duration and restart automatically after the ttrpc connection is lost, then plugin will be auto-reregistered to the adaptation.
=> stub: support restart after stub stopped

pkg/adaptation/adaptation.go, pkg/adaptation/plugin.go
Close the connection to the plugin if initial synchronization fails, like we do for all other failures considered unrecoverable.
=> adaptation: close plugin if initial synchronization fails.

pkg/adaptation/adaptation_suite_test.go, pkg/adaptation/result.go, pkg/api/helpers.go
This PR fixes the remaining problems in PR #87, and adds a missing test case for mount removal.
=> fixes: fix mount removal in adjustments, add a test case for it.

pkg/adaptation/adaptation.go
For plugins registered with nri.sock, NRI will send the full set of pods and containers after starting.
https://github.com/containerd/nri/blob/83295992ed466e5589a1a83ba3ad2bd6b6feb199/pkg/adaptation/adaptation.go#L405-L430
For pre-installed plugins, it is still necessary to synchronize the sandboxes and containers data to the plugin after launch，otherwise the plugin will never be able to get information about existing resources
=> sync sandboxes and containers after starting the pre-installed plugins

pkg/runtime-tools/generate/generate.go, pkg/runtime-tools/generate/generate_suite_test.go
Existing OOMScoreAdj on the incoming spec should not be cleared.
Fixes https://github.com/containerd/nri/issues/117
=>  generate: do not set OOMScoreAdj if no adjustment

pkg/adaptation/plugin.go, pkg/adaptation/plugin_type.go
Follow-up on: https://github.com/containerd/nri/pull/121#discussion_r1872009094
PTAL @mikebrow
=> Add dedicated plugin type struct

pkg/api/resources.go
Both FromOCILinuxResources and FromCRILinuxResources were not copying the Unified map, so NRI plugins don't have access to Unified for both the pod or the container.
=> pkg/api: Copy Unified map

Makefile
Don't let symlinks on $(PWD) break dockerized tinygo builds of the sample WASM plugin so easily.
=> Makefile: symlink-safer tinygo docker builds.

pkg/adaptation/adaptation.go, pkg/adaptation/plugin.go
Don't use the default wazero runtime configuration. Instead use one with `WithCloseOnContextDone(true) in order for calls to WASM plugins to properly obey context deadlines, which otherwise they don't. Also, once a WASM plugin is closed (for instance due to a request processing timeout), mark the plugin closed so it gets properly removed from the list of active plugins.
Fixes #138.
=> adaptation: honor context deadline in WASM runtime/plugins.

pkg/stub/stub.go
If we get an event for which we have no handler, return an empty response with a nil error, instead of a nil response with a nil error. Doing the latter would result in a ttrpc marshalling error being returned, something like this `rpc error: code = Unknown desc = ttrpc: marshal called with nil`.
=> stub: don't return nil response without an error.

.github/actions/install-go/action.yml, .github/workflows/ci.yml
This patch series
- updates `project-checks` to use latest tagged version
- adopts local `install-go` action from containerd
- updates the CI workflow to use same golang versions for linting and tests as containerd 1.7
- updates `golangci-lint` version
These version bumps should fix failing project-checks in CI.
=> .github: update project-checks, use local install-go action in CI workflow.

plugins/device-injector/README.md, plugins/device-injector/device-injector.go, plugins/device-injector/device-injector_test.go, plugins/device-injector/sample-device-inject.yaml, plugins/network-device-injector/README.md, plugins/network-device-injector/network-device-injector.go, plugins/network-device-injector/sample-network-device-inject.yaml, plugins/ulimit-adjuster/README.md, plugins/ulimit-adjuster/adjuster.go, plugins/ulimit-adjuster/adjuster_test.go
The nri.io domain is not owned or controlled by CNCF and its use should be discouraged.  This commit adds support for the new noderesource.dev domain, which is a CNCF-owned domain.
=> plugins: use noderesource.dev domain

pkg/stub/stub.go
It is not a good practice for a library to unilaterally decide to terminate the entire program and, since it is imported, is super hard to debug for nri plugins authors that only see the program exit without any obvious reason.
Change-Id: Ic72612d4e8421a2eb301d33dda760765461929d7
=> don't exit on close

README.md, go.mod, pkg/adaptation/adaptation.go, pkg/adaptation/adaptation_suite_test.go, pkg/adaptation/api.go, pkg/adaptation/builtin/plugin.go, pkg/adaptation/plugin.go, pkg/adaptation/plugin_type.go, pkg/adaptation/suite_test.go, pkg/api/owners.go, pkg/api/validate.go, pkg/plugin/annotations.go, plugins/default-validator/builtin/plugin.go, plugins/default-validator/default-validator.go, plugins/default-validator/default-validator_test.go
This PR is stacked on #169 and #170.
This PR is the third in a stack which splits up #163 into multiple PRs, which collectively implement [configurable restrictions](https://github.com/containerd/nri/issues/137) using the [proposed pluggable validation API](https://github.com/containerd/nri/issues/137#issuecomment-2673008626) and a builtin default validator plugin.
This PR
- adds support for built-in plugins,
- implements default validation using a built-in default-validator plugin, and
- provides an externally built version of the default-validator plugin [note: removed in latest iteration]
/cc @chrishenzie
=> [pluggable-validation / 3]: implement default validator.

.github/workflows/ci.yml
There is no reason to stick to 1.24.3, means we can re-introduce the go1.24.x tag to allow newer ones in CI.
=> ci: use latest go patch version

MAINTAINERS, README.md
Pending https://github.com/containerd/project/pull/148
=> Add maintainers file

pkg/adaptation/result.go, pkg/api/resources.go, pkg/runtime-tools/generate/generate.go
This is a very useful feature for cases where we'd like to give wildcard device permissions to the cgroup, e.g. `--device-cgroup-rule 'c *:* rwm'` which is possible in both Podman and Docker.
Found out the hard way that `Linux.Resources.Devices` are not processed at all.
If I understood the claim logic correctly, it is to prevent multiple plugins from overriding each other. But the cgroup rules array is a layered permission list, e.g. it starts with a deny all rule and allow rules are appended so different plugins may append different rules. That's why I didn't add a `claimDeviceCgroup` but happy to change.
I've validated this change with containerd `1.7.27` that has this patch on top of NRI `0.8.0`.
=> Include linux device cgroups in adjustment logic

README.md
https://github.com/containerd/nri/issues/186
=> [doc] mention support for oci's `unified` config map in readme

README.md, plugins/template/README.md, plugins/wasm/README.md
Also add minimal readme for the template and wasm plugins.
The default-validator plugin is left out as it cannot be built as an external plugin (without changes).
=> readme: list all sample plugins

Makefile
Add missing targets to build also the `network-device-injector` and `network-logger` plugins.
=> Makefile: build all plugins by default.

plugins/hook-injector/hook-injector.go
Provides debug logs from the hooks manager, too.
=> plugins/hook-injector: more verbosity on -verbose

Makefile
Use a pattern rule and have a special case for the WASM plugin. Also remove the wildcard so that the plugin(s) are rebuilt e.g. in the case dependencies are updated.
=> Makefile: simplify plugin build make targets

Makefile, hack/Dockerfile.buildproto
Makes it possible to build api files without contaminating the host system.
=> Add dockerized target for building proto files

examples/go.mod, examples/go.sum, go.mod, plugins/device-injector/go.mod, plugins/differ/go.mod, plugins/hook-injector/go.mod, plugins/logger/go.mod, plugins/network-device-injector/go.mod, plugins/network-logger/go.mod, plugins/template/go.mod, plugins/ulimit-adjuster/go.mod, plugins/v010-adapter/go.mod, plugins/wasm/go.mod
Require the lowest available go version to increase compatibility with other projects. 
Per: https://github.com/containerd/nri/commit/f6f8d03795231aae8c7eab14fcadfa051b93d713#r164441839
=> Downgrade go to require 1.24.0

pkg/adaptation/api.go, pkg/api/event.go, pkg/net/multiplex/mux.go
Drop unnecessary nolint directives and unify the style of remaining ones to match the rest of the codebase (and the golangci-lint documentation).
=> chore: clean and unify nolint directives

.gitignore
A small nit, but helps a lot when working with goland editor.
=> nit: Add .idea folder to gitignore

.golangci.yml
Disable:
QF1008: could remove embedded field "Generator" from selector
=> golangci: disable QF1008 from staticcheck linter

.github/workflows/images.yml
Image signatures can be verified with cosign. An example for the rolling unstable image for the template plugin:
```bash
cosign verify ghcr.io/containerd/nri/plugins/template:unstable \
--certificate-identity-regexp "https://github.com/containerd/nri/.*" \
--certificate-oidc-issuer https://token.actions.githubusercontent.com \
| jq .
```
=> ci: enable image signing

pkg/adaptation/result.go
Refactored resource processing logic by extracting `adjustMemoryResource` and `adjustCPUResource` helper functions to eliminate code duplication.
- Added `adjustMemoryResource` function for memory resource operations
- Added `adjustCPUResource` function for CPU resource operations  
- Updated `adjustResources` and `updateResources` to use new helpers
=> extract memory and CPU resource helpers

plugins/logger/nri-logger.go
Let the stub determine which events the logger plugin subscribes to, to fix a recently introduced startup failure.
Ever since support for the new pod update events has been merged, unless the event subscription mask is overidden with the `--events` command line option, the sample logger plugin fails to start up with the following error message:
> plugin exited with error internal error: unhandled events UpdatePodSandbox,PostUpdatePodSandbox (0x1800)
This patch should fix that.
=> plugins/logger: fix default event subscription mask.

.github/workflows/ci.yml, .github/workflows/codeql.yml, Makefile, scripts/install-protobuf
Install (and use) protoc and plugins under build/tools in the source tree in an attempt to ensure that the correct version of the tooling is always used.
=> Install protoc locally in the source tree

pkg/adaptation/adaptation_suite_test.go
The current tests for collecting container resource adjustments starts out with fully empty container memory and CPU resources. This allows unintended changes to sneak in unnoticed to the semantics of collected adjustments (see #210). Let's make this less likely by starting with populated initial resources.
=> adaptation: test with populated initial resources.

Makefile, hack/Dockerfile.buildproto, scripts/install-protobuf
Ditch the makefile pattern rule which simply doesn't work in scenarios where both the source and the build targets are stored in the git repo (as git operations mangle the time stamps).
So much grey hair avoided when the stuff just force generates everything instead of leaving you wonder why the tools didn't work as expected.
=> Makefile: build proto files unconditionally

plugins/wasm/plugin.go
`main` is not called anymore with a WASI reactor, means we have to use `init()` and provide an empty `main()` instead.
Fixes https://github.com/containerd/nri/issues/236
=> Fix wasm example

pkg/adaptation/suite_test.go
A plugin having received a sync request is not enough to ensure it has been fully registered on the runtime side (IOW appended to the list of active plugins). When we are waiting for test plugins to start up, use an extra plugin synchronization block/unblock to ensure they are fully registered.
=> adaptation: ensure sync'ed plugins are fully registered in tests.
